image:
  repository: ghcr.io/litong5969/paddleocr-server
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

replicaCount: 1

env:
  APP_HOST: "0.0.0.0"
  APP_PORT: "5000"
  OCR_LANG: "ch"
  OCR_VERSION: "PP-OCRv4"
  OCR_USE_ANGLE_CLS: "true"
  OCR_USE_GPU: "false"
  PADDLEOCR_HOME: "/root/.paddleocr"
  METRICS_ENABLED: "true"
  OCR_WARMUP_ON_START: "true"
  OCR_WARMUP_TIMEOUT_SEC: "20"
  OCR_BATCH_MAX_FILES: "8"
  MAX_IMAGE_SIZE_MB: "10"
  MAX_BATCH_TOTAL_MB: "20"

resources: {}

useGpu: false

persistence:
  enabled: false
  size: 5Gi
  storageClass: ""

ingress:
  enabled: false
  className: ""
  hosts:
    - host: paddleocr.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
