apiVersion: v1
kind: Service
metadata:
  name: paddleocr-server
  labels:
    app: paddleocr-server
spec:
  type: ClusterIP
  selector:
    app: paddleocr-server
  ports:
    - name: http
      port: 80
      targetPort: 5000

